### PR TITLE
add support for target option

### PR DESCRIPTION
**Pull request by spookiej**
I have a use case where I cannot delete all resources on destroy. So that terraform behaves nicely I need to limit the resources when using the target option.

Hopefully this looks good to you, otherwise let me know if you want me to implement any more tests, etc.

### CODE REVIEW

**Comment by spookiej** [comment]
@googlebot I signed it!

**Comment by ludoo** [comment]
Looks good, thanks for the contribution! I will release on pypi ASAP.

**Comment by ludoo** [comment]
https://pypi.org/project/tftest/1.5.0/

**Comment by spookiej** [comment]
Awesome! Thanks for that

**Pull request merged**
