### PR TITLE
Adds support for the upgrade argument of the init command

### LINKED ISSUE #39: Options for managing `.terraform.lock.hcl`?
I occasionally run into an issue with the `.terraform.lock.hcl`, where I either need to pass `-upgrade` to terraform init, or just remove the lock file to let it regenerate. It doesn't look to me like `parse_args()` is supporting the `-upgrade` option? I was checking to see if I could (ab)use `extra_files` to remove it after the test, but that doesn't seem like a great option... Not sure if I'm missing something obvious here...

Fwiw, the issue appears to be when I run tests at some point in time, which generates the lock file on my machine. Then I add some new feature to the module later and re-run the tests. The provider version in the lockfile does not yet support the feature, so the test fails. And like I said, manually deleting the lock file gets it working, or manually running `terraform init -upgrade`. This is a re-usable module, not a root module, so the test configs do not commit the lock file.

### PR DESCRIPTION
**Pull request by lorengordon**
Closes #39

### CODE REVIEW

**Comment by lorengordon** [comment]
i can't figure out the cla. i have many google accounts, but it's not selecting the correct one.

**Comment by ludoo** [comment]
Hey Gordon, thanks a lot for this! Can you try signing the CLA in an incognito window? If that fails, I can try checking internally if there's some magic to unblock this.

**Comment by lorengordon** [comment]
@ludoo ok i think that worked. how to retrigger the check?

**Comment by ludoo** [comment]
I did, all good! Let me check it over quickly and I'll merge. Do you need a pypi release?

**Comment by lorengordon** [comment]
oh there it goes, all green now!

**Review by ludoo — APPROVED** [review]

**Comment by lorengordon** [comment]
yeah, we pin installs to pypi release versions, so a release would be awesome

**Comment by ludoo** [comment]
Ok, let me do that. I will ping here when done.

**Comment by ludoo** [comment]
I just pushed it to pypi, let me know if anything is amiss, and thanks again for the PR!

https://pypi.org/project/tftest/1.6.3/

**Pull request merged**
