### PR TITLE
Terragrunt support

### PR DESCRIPTION
**Pull request by davidtam**
I merged master into the branch and fixed a few things - now I am able to run all the tests and passed

### CODE REVIEW

**Comment by ludoo** [comment]
Let me know when you think this is ready for merging in the Terragrunt branch, then we'll pick it up from there. And could you check the CLA notice above plz? :)

**Comment by davidtam** [comment]
> Let me know when you think this is ready for merging in the Terragrunt branch, then we'll pick it up from there. And could you check the CLA notice above plz? :)

Hi for CLA I have already signed (`We found a Contributor License Agreement for you (the sender of this pull request)`), what else do I need to do there?

I could spend a bit more time refactor today(but IMHO the PR is already quite / too big for review!).  but what are your thoughts for the current state?
I could (and thinking about) continue with the following:

- There are a few patterns for the kwargs parsing and could simplify on that
- I think a lot of the calls that in the code based that are currently splitted between terraform and terragrunt could be merged
   - I think the special case for output could be shared
   - the additional tg params would do no harm when running terraform
   - but of course, it makes it less verbose, but perhaps less clear cut (maybe, e.g. a bit more difficult to debug if merged?)

@ludoo what do you think?

**Comment by davidtam** [comment]
ok I am done with it - the test runs locally for me (but I permission to see the test run from GCP, pls let me know what is failing).  @ludoo do you mind taking a look at the rest also?

**Comment by ludoo** [comment]
Failing test:

```
run_all_plan_output = [<tftest.TerraformPlanOutput object at 0x7f088ef00b70>, <tftest.TerraformPlanOutput object at 0x7f088ef00c50>, <tftest.TerraformPlanOutput object at 0x7f088ef00d30>]

    def test_run_all_plan(run_all_plan_output):
      for plan in run_all_plan_output:
>       assert plan.outputs['triggers'] == [{'name': 'one', 'template': 'sample template one'},
                                            {'name': 'two', 'template': 'sample template two'}]
E       AssertionError: assert [{'name': 'fo...emplate foo'}] == [{'name': 'on...emplate two'}]
E         At index 0 diff: {'name': 'foo', 'template': 'sample template foo'} != {'name': 'one', 'template': 'sample template one'}
E         Right contains one more item: {'name': 'two', 'template': 'sample template two'}
E         Full diff:
E         - [{'name': 'foo', 'template': 'sample template foo'}]
E         ?            - ^                                - ^  ^
E         + [{'name': 'one', 'template': 'sample template one'},
E         ?             ^^                                 ^^  ^...
E         
E         ...Full output truncated (2 lines hidden), use '-vv' to show

test/test_tg_all.py:69: AssertionError
```

**Comment by ludoo** [comment]
I'm happy to merge, then give you access to the branch so we can iron out the remaining details. WDYT?

**Comment by davidtam** [comment]
> I'm happy to merge, then give you access to the branch so we can iron out the remaining details. WDYT?

ah ok yes pls that would be great

**Comment by ludoo** [comment]
Done!

Can you add the relevant Terragrunt bits to the README, and make sure all tests pass? I'll go over the code ASAP (hopefully between tonight and tomorrow), so we can try and merge this in the next few days. And thanks for all the hard work! :)

**Pull request merged**
